name: assurancy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.5.4
  local_auth: ^2.3.0
  image_picker: ^1.1.2
  signature: ^5.3.0
  qr_flutter: ^4.1.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  http_parser: ^4.0.2
  geolocator: ^11.0.0
  jwt_decoder: ^2.0.1       # ← AJOUTE pour décoder le token JWT

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true